export const animeGenres = [
    "Action",
    "Adventure",
    "Cars",
    "Comedy",
    "Dementia",
    "Demons",
    "Mystery",
    "Drama",
    "Ecchi",
    "Fantasy",
    "Game",
    "Hentai",
    "Historical",
    "Horror",
    "Kids",
    "Magic",
    "Martial Arts",
    "Mecha",
    "Music",
    "Parody",
    "Samurai",
    "Romance",
    "School",
    "Sci Fi",
    "Shoujo",
    "Shoujo Ai",
    "Shounen",
    "Shounen Ai",
    "Space",
    "Sports",
    "Super Power",
    "Vampire",
    "Yaoi",
    "Yuri",
    "Harem",
    "Slice Of Life",
    "Supernatural",
    "Military",
    "Police",
    "Psychological",
    "Thriller",
    "Seinen",
    "Josei",
];
